Tugas Selasa Math for AI (Materi Operasi Matrix)

Kelas : Ragnarok

Universitas : Bina Nusantara

Soal

In [1]:
import numpy as np 
import numpy.linalg as nlin

A = np.array([[1,2], [7,8]])
B = np.array([[3,5], [1,6]])

A,B

(array([[1, 2],
        [7, 8]]), array([[3, 5],
        [1, 6]]))

1.2*A

In [2]:
2*A

array([[ 2,  4],
       [14, 16]])

In [3]:
2+A

array([[ 3,  4],
       [ 9, 10]])

3.A+B

In [4]:
A+B

array([[ 4,  7],
       [ 8, 14]])

4.A-B

In [5]:
A-B

array([[-2, -3],
       [ 6,  2]])

5. Determinan A

In [6]:
nlin.det(A)

-6.0

6. Invers dari B, simpan jadi matrix D

In [7]:
D = nlin.inv(B)

D

array([[ 0.46153846, -0.38461538],
       [-0.07692308,  0.23076923]])

7. Transpose D

In [8]:
np.transpose(D)

array([[ 0.46153846, -0.07692308],
       [-0.38461538,  0.23076923]])

8. Nilai eigen dan vektor eigen dari A  dan B

In [10]:
nilaiEigA, vektorEigA=nlin.eig(A)

print("Nilai Eig matrix A :\n",nilaiEigA)
print("\nVektor Eig matrix A :\n, vektorEigA")

Nilai Eig matrix A :
 [-0.62347538  9.62347538]

Vektor Eig matrix A :
, vektorEigA


In [11]:
nilaiEigB, vektorEigB=nlin.eig(B)

print("Nilai Eig matrix B :\n",nilaiEigB)
print("\nVektor Eig matrix B :\n", vektorEigB)

Nilai Eig matrix B :
 [1.8074176 7.1925824]

Vektor Eig matrix B :
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]
